### ISSUE TITLE
Broken Link Tutorial build-raw

### ISSUE THREAD

**Issue by dvdkroft** [iburzynski/cardano-cli-guru#1]
File: tutorial/02-build-raw.md

Broken link: See the [Starting and syncing the node](https://github.com/iburzynski/cardano-cli-guru/blob/main/tutorial/00-installation.md#starting-and-syncing-the-node) section of the installation guide if you face any difficulty.

**Comment by iburzynski** [comment]
Thanks! Fixed in https://github.com/iburzynski/cardano-cli-guru/commit/d8025adeec64384da69fa676b5428d1bb4cc6004
