### ISSUE TITLE
07-nft.md

### ISSUE THREAD

**Issue by dvdkroft** [iburzynski/cardano-cli-guru#2]
I believe the following:
DEADLINE=$(eval 22121952 + 3600)

Should be changed to:
DEADLINE=$(expr 22121952 + 3600)

At least on my Mac this is resulting in:
zsh: command not found: 22121952

**Comment by iburzynski** [comment]
You're right, thanks for catching this!

Fixed in https://github.com/iburzynski/cardano-cli-guru/commit/1467d8c0f7a13e5f87e6fde78ebdb38cccfe8709
